### ISSUE TITLE
error in doc for transpose

### ISSUE THREAD

**Issue by frswemil** [FreeFem/FreeFem-doc#14]
I think there is an error on the definition of transpose in the documentation.

It is indicated that the operator ' returns the transpose, and '' the hermitian transpose. 

In my version of FreeFem++ (3.610001), the operator ' returns the transpose if the matrix is real, and hermitian transpose if the matrix is complex. This behavior is observed both for matrix and complex[int,int] types.

The operator '' is not recognized.

**Comment by sgarnotel** [comment]
This is effectively a mistake (editor autocompletion).

Thanks a lot for the feedback
