### ISSUE TITLE
Suggested amendments to the documentation

### ISSUE THREAD

**Issue by paolopiers** [FreeFem/FreeFem-doc#15]
Hello,
I would like to report these bugs I found in version 4.0 documentation.
The page number refers to the number you find on the bottom right corner of each page.

page 150: text out of bounds
page 180: bc[] is not defined
page 517: the paper you should refer to is the one by Hintermuller, Ito and Kunisch (see the file VI.edp)

Thanks and best regards,

Paolo

**Comment by sgarnotel** [comment]
Thanks a lot for your feedback.

Some parts of the documentation are quite old and are not anymore related to the surrounding content (error in p. 180). We will upgrade that as soon as possible

**Comment by franckl** [comment]
page 150 is also fixed : https://github.com/FreeFem/FreeFem-doc/commit/b9bf343f52769314e836cdbe746baed4f6a149a0
