### ISSUE TITLE
Small typo in documentation

### ISSUE THREAD

**Issue by gregzanch** [FreeFem/FreeFem-doc#23]
The documentation for [Free boundary problems](https://doc.freefem.org/models/free-boundary-problems.html#free-boundary-problems) shows this code at the top

```
// Parameters
real L = 10; //length
real hr = 2.1; //left height
real hl = 0.35; //right height
int n = 4;
```

I believe the left and right height variable names are swapped.

**Comment by AFourmont** [comment]
Thank for this correction
