### ISSUE TITLE
FreeFem + Paraview

### ISSUE THREAD

**Issue by annabellecollin** [FreeFem/FreeFem-doc#24]
I use the version v4.5 of FreeFem++.
When I run this small part of code:
****** BEGIN ******
load "medit"
load "msh3"
load "iovtk" 
mesh3 Th = cube(10, 10, 10);
savemesh(Th,"test.mesh");
mesh3 Th2;
Th2 = readmesh3("test.mesh");
savevtk("test.vtk",Th);
savevtk("test2.vtk",Th2);
****** END ******
Both files test.vtk and test2.vtk can not be opened by Paraview (version 5.8.0). 
It works with 2D mesh (and with surface mesh) but not with 3D mesh.
Thank you very much for your help.

**Comment by prj-** [comment]
This repository is for the documentation of FreeFEM, please ask your general questions over at https://github.com/FreeFem/FreeFem-sources.
You can fix your code using the `.vtu` extension, i.e.:
```
savevtk("test.vtu",Th);
savevtk("test2.vtu",Th2);
```

**Comment by annabellecollin** [comment]
Ok sorry for the mistake. 
Thanks! It works.
